# Generated by Django 6.0.3 on 2026-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.TextField(default='')),
                ('running', models.BooleanField(default=False)),
                ('done', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('current', models.CharField(default='', max_length=500)),
                ('newly_indexed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statut indexation',
            },
        ),
    ]
